// Auto-generated by scripts/gen-tokens.js. Do not edit by hand.
// Source: ../locals-shared/tokens/design.json
//
// Run `scripts/sync-tokens.sh` to regenerate. Three-native pattern: web
// + iOS + Android each vendor a synced copy of the shared tokens.

import SwiftUI
import UIKit

public enum DesignTokens {
  /// Resolve a colour by trait-collection at draw time so iOS handles
  /// dark-mode flips without a `@Environment(\.colorScheme)` push.
  static func dual(light: Color, dark: Color) -> Color {
    Color(uiColor: UIColor { trait in
      trait.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
    })
  }

  public enum Brand {
    public static let mustard = SwiftUI.Color(red: 0.7686, green: 0.6039, blue: 0.2471)
    public static let mustard_deep = SwiftUI.Color(red: 0.6078, green: 0.4784, blue: 0.1765)
    public static let cream = SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882)
    public static let cream_warm = SwiftUI.Color(red: 0.9412, green: 0.9098, blue: 0.8314)
    public static let ink = SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627)
  }

  public enum BG {
    public static let default = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882, opacity: 1.00),
      dark:  SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627, opacity: 1.00)
    )
    public static let elevated = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.9412, green: 0.9098, blue: 0.8314, opacity: 1.00),
      dark:  SwiftUI.Color(red: 0.1647, green: 0.1333, blue: 0.0941, opacity: 1.00)
    )
    public static let subtle = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.8471, green: 0.8118, blue: 0.7255, opacity: 1.00),
      dark:  SwiftUI.Color(red: 0.2000, green: 0.1647, blue: 0.1216, opacity: 1.00)
    )
    public static let accent = SwiftUI.Color(red: 0.7686, green: 0.6039, blue: 0.2471)
  }

  public enum FG {
    public static let default = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627, opacity: 1.00),
      dark:  SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882, opacity: 1.00)
    )
    public static let muted = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627, opacity: 0.62),
      dark:  SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882, opacity: 0.62)
    )
    public static let trace = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627, opacity: 0.32),
      dark:  SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882, opacity: 0.32)
    )
    public static let onAccent = SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882)
  }

  public enum Border {
    public static let subtle = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627, opacity: 0.10),
      dark:  SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882, opacity: 0.10)
    )
    public static let default = DesignTokens.dual(
      light: SwiftUI.Color(red: 0.1216, green: 0.0941, blue: 0.0627, opacity: 0.20),
      dark:  SwiftUI.Color(red: 0.9098, green: 0.8745, blue: 0.7882, opacity: 0.20)
    )
  }

  public enum Space {
    public static let zero: CGFloat = 0
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 16
    public static let xl: CGFloat = 20
    public static let xxl: CGFloat = 24
    public static let huge: CGFloat = 32
    public static let _10: CGFloat = 40
    public static let _12: CGFloat = 48
    public static let _16: CGFloat = 64
    public static let _20: CGFloat = 80
    public static let _24: CGFloat = 96
    public static let _32: CGFloat = 128
  }

  public enum Radius {
    public static let none: CGFloat = 0
    public static let sm: CGFloat = 4
    public static let md: CGFloat = 8
    public static let lg: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let xxl: CGFloat = 24
    public static let full: CGFloat = 9999
  }

  public enum Size {
    public static let xs: CGFloat = 12
    public static let sm: CGFloat = 14
    public static let base: CGFloat = 16
    public static let lg: CGFloat = 18
    public static let xl: CGFloat = 22
    public static let xxl: CGFloat = 28
    public static let h2: CGFloat = 36
    public static let h1: CGFloat = 48
    public static let hero: CGFloat = 64
  }

  public enum Motion {
    public static let fast: Double = 0.12
    public static let base: Double = 0.20
    public static let slow: Double = 0.32
  }
}
