#!/usr/bin/env node
// Read locals-shared/tokens/design.json, emit Swift DesignTokens.swift.
// Stdout is the file. Stays minimal on purpose - the source of truth is the
// shared JSON; this is mechanical translation.

const fs = require('fs');
const path = process.argv[2];
if (!path) { console.error('usage: gen-tokens.js <design.json>'); process.exit(1); }
const j = JSON.parse(fs.readFileSync(path, 'utf8'));

function hexToRGB(hex) {
  const h = hex.replace('#', '');
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return [r, g, b];
}
function rgbaParse(s) {
  // "rgba(31,24,16,0.62)" -> {r, g, b, a}
  const m = s.match(/rgba?\(([^)]+)\)/);
  if (!m) return null;
  const [r, g, b, a] = m[1].split(',').map(s => parseFloat(s.trim()));
  return [r / 255, g / 255, b / 255, a == null ? 1 : a];
}
function emitColor(name, v) {
  if (typeof v === 'string' && v.startsWith('#')) {
    const [r, g, b] = hexToRGB(v);
    return `    public static let ${name} = SwiftUI.Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
  }
  if (typeof v === 'string' && v.startsWith('rgba')) {
    const rgba = rgbaParse(v);
    if (rgba) {
      const [r, g, b, a] = rgba;
      return `    public static let ${name} = SwiftUI.Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, opacity: ${a.toFixed(2)})`;
    }
  }
  return null;
}
function emitDual(name, light, dark) {
  const rgbaParseOrHex = (s) => s.startsWith('#') ? [...hexToRGB(s), 1] : rgbaParse(s);
  const [lr, lg, lb, la] = rgbaParseOrHex(light);
  const [dr, dg, db, da] = rgbaParseOrHex(dark);
  return `    public static let ${name} = DesignTokens.dual(
      light: SwiftUI.Color(red: ${lr.toFixed(4)}, green: ${lg.toFixed(4)}, blue: ${lb.toFixed(4)}, opacity: ${la.toFixed(2)}),
      dark:  SwiftUI.Color(red: ${dr.toFixed(4)}, green: ${dg.toFixed(4)}, blue: ${db.toFixed(4)}, opacity: ${da.toFixed(2)})
    )`;
}

const lines = [];
lines.push('// Auto-generated by scripts/gen-tokens.js. Do not edit by hand.');
lines.push('// Source: ../locals-shared/tokens/design.json');
lines.push('//');
lines.push('// Run `scripts/sync-tokens.sh` to regenerate. Three-native pattern: web');
lines.push('// + iOS + Android each vendor a synced copy of the shared tokens.');
lines.push('');
lines.push('import SwiftUI');
lines.push('import UIKit');
lines.push('');
lines.push('public enum DesignTokens {');
lines.push('  /// Resolve a colour by trait-collection at draw time so iOS handles');
lines.push('  /// dark-mode flips without a `@Environment(\\.colorScheme)` push.');
lines.push('  static func dual(light: Color, dark: Color) -> Color {');
lines.push('    Color(uiColor: UIColor { trait in');
lines.push('      trait.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)');
lines.push('    })');
lines.push('  }');
lines.push('');
lines.push('  public enum Brand {');
for (const [k, v] of Object.entries(j.color.brand)) {
  const line = emitColor(k, v.$value);
  if (line) lines.push(line);
}
lines.push('  }');
lines.push('');
lines.push('  public enum BG {');
for (const [k, v] of Object.entries(j.color.bg)) {
  if (typeof v.$value === 'string') {
    const line = emitColor(k, v.$value);
    if (line) lines.push(line);
  } else {
    lines.push(emitDual(k, v.$value.light, v.$value.dark));
  }
}
lines.push('  }');
lines.push('');
lines.push('  public enum FG {');
for (const [k, v] of Object.entries(j.color.fg)) {
  const key = k === 'on_accent' ? 'onAccent' : k;
  if (typeof v.$value === 'string') {
    const line = emitColor(key, v.$value);
    if (line) lines.push(line);
  } else {
    lines.push(emitDual(key, v.$value.light, v.$value.dark));
  }
}
lines.push('  }');
lines.push('');
lines.push('  public enum Border {');
for (const [k, v] of Object.entries(j.color.border)) {
  if (typeof v.$value === 'string') {
    const line = emitColor(k, v.$value);
    if (line) lines.push(line);
  } else {
    lines.push(emitDual(k, v.$value.light, v.$value.dark));
  }
}
lines.push('  }');
lines.push('');
lines.push('  public enum Space {');
const spaceMap = { '0': 'zero', '1': 'xs', '2': 'sm', '3': 'md', '4': 'lg', '5': 'xl', '6': 'xxl', '8': 'huge', '10': '_10', '12': '_12', '16': '_16', '20': '_20', '24': '_24', '32': '_32' };
for (const [k, v] of Object.entries(j.space)) {
  const name = spaceMap[k] || `_${k}`;
  lines.push(`    public static let ${name}: CGFloat = ${v.$value}`);
}
lines.push('  }');
lines.push('');
lines.push('  public enum Radius {');
for (const [k, v] of Object.entries(j.radius)) {
  const name = k === '2xl' ? 'xxl' : k;
  const val = name === 'full' ? '9999' : v.$value;
  lines.push(`    public static let ${name}: CGFloat = ${val}`);
}
lines.push('  }');
lines.push('');
lines.push('  public enum Size {');
const sizeMap = { 'xs': 'xs', 'sm': 'sm', 'base': 'base', 'lg': 'lg', 'xl': 'xl', '2xl': 'xxl', '3xl': 'h2', '4xl': 'h1', '5xl': 'hero' };
for (const [k, v] of Object.entries(j.type.size)) {
  const name = sizeMap[k] || `_${k}`;
  lines.push(`    public static let ${name}: CGFloat = ${v.$value}`);
}
lines.push('  }');
lines.push('');
lines.push('  public enum Motion {');
lines.push('    public static let fast: Double = 0.12');
lines.push('    public static let base: Double = 0.20');
lines.push('    public static let slow: Double = 0.32');
lines.push('  }');
lines.push('}');
lines.push('');
process.stdout.write(lines.join('\n'));
